DROP TABLE IF EXISTS audios CASCADE;

CREATE TABLE audios (
    id int(11) NOT NULL auto_increment,
    placeId varchar(500) NOT NULL,
    audio LONGBLOB NOT NULL,
    nome VARCHAR(200) NOT NULL,
    PRIMARY KEY(id)
)ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;